### ISSUE TITLE
leveldb.go 中的BatchPut函数感觉是写错了

### ISSUE THREAD

**Issue by chennrufeng** [xjdrew/redis-persist#16]
for i := 0; i < sz-1; i++ {
		batch.Put(args[i], args[i+1])
	}
#是否该写成下面这样？
for i := 0; i < sz-1; i = i + 2 {
		batch.Put(args[i], args[i+1])
	}

**Comment by spin6lock** [comment]
是写错了……

发自我的 iPhone
